
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  dockerId: LHGRegistry 
  imageName: hello-world
  pswd: 2auCgbd24PKEwJ4SgKMYZv8CazOuU6+q
steps:
- script: |
    docker build -t $(dockerId)/$(imageName)
    docker login -u $(dockerId) -p $(pswd)
    docker tag hello-world <lhgregistry.azurecr.io>/hello-world:v1
    docker push <lhgregistry.azurecr.io>/hello-world:v1




