
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: nikhilbhaskara 
  imageName: helloworld
steps:
- script: |
    docker build -t $(dockerId)/$(imageName)
    docker login -u $(dockerId) -p $(pswd)
    docker tag $(imageName):latest $(imageName):latest
    docker push $(dockerId)/$(imageName)




